name: Deploy
on: push
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: astro
        name: Setup Astro
        uses: withastro/action@v2
        with:
          node-version: 21
          package-manager: npm
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deploy
        name: Deploy pages
        uses: actions/deploy-pages@v4
